/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import javax.swing.ImageIcon;

/**
 *
 * @author IKHBAL
 */
public class DaftarListMenu extends javax.swing.JFrame {

    /**
     * Creates new form DaftarListMenu
     */
    public DaftarListMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mDaftarMenu = new javax.swing.JLabel();
        mNoKantinSatu = new javax.swing.JLabel();
        mMenuKantinSatu = new javax.swing.JLabel();
        mMenuKantinDua = new javax.swing.JLabel();
        mMenuKantinTiga = new javax.swing.JLabel();
        mMenuKantinEmpat = new javax.swing.JLabel();
        mMenuKantinLima = new javax.swing.JLabel();
        mNoKantinDua = new javax.swing.JLabel();
        mMenuKantinEnam = new javax.swing.JLabel();
        mMenuKantinTujuh = new javax.swing.JLabel();
        mMenuKantinDelapan = new javax.swing.JLabel();
        mMenuKantinSembilan = new javax.swing.JLabel();
        mMenuKantinSepuluh = new javax.swing.JLabel();
        mNoKantinTiga = new javax.swing.JLabel();
        mMenuKantinSebelas = new javax.swing.JLabel();
        mMenuKantinDuaBelas = new javax.swing.JLabel();
        mMenuKantinTigaBelas = new javax.swing.JLabel();
        mMenuKantinEmpatBelas = new javax.swing.JLabel();
        mMenuKantinLimaBelas = new javax.swing.JLabel();
        mNoKantinEmpat = new javax.swing.JLabel();
        mMenuKantinEnamBelas = new javax.swing.JLabel();
        mMenuKantinTujuhBelas = new javax.swing.JLabel();
        mMenuKantinDelapanBelas = new javax.swing.JLabel();
        mMenuKantinSembilanBelas = new javax.swing.JLabel();
        mMenuKantinDuaPuluh = new javax.swing.JLabel();
        mNoKantinLima = new javax.swing.JLabel();
        mMenuKantinDuaSatu = new javax.swing.JLabel();
        mMenuKantinDuaDua = new javax.swing.JLabel();
        mMenuKantinDuaTiga = new javax.swing.JLabel();
        mMenuKantinDuaEmpat = new javax.swing.JLabel();
        mMenuKantinDuaLima = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mDaftarMenu.setText("Daftar Menu Kantin");

        mNoKantinSatu.setText("1. Kantin Kreasi");

        mMenuKantinSatu.setText("Sosis Bakar");

        mMenuKantinDua.setText("Nasi Goreng");

        mMenuKantinTiga.setText("Donat Kukus");

        mMenuKantinEmpat.setText("Somay Bandung");

        mMenuKantinLima.setText("Bubur Ayam");

        mNoKantinDua.setText("2. Kantin Barokah");

        mMenuKantinEnam.setText("Jus Mangga");

        mMenuKantinTujuh.setText("Jus Buah Naga");

        mMenuKantinDelapan.setText("Es Campur");

        mMenuKantinSembilan.setText("Pop Ice");

        mMenuKantinSepuluh.setText("Air Mineral");

        mNoKantinTiga.setText("3. Kantin WK");

        mMenuKantinSebelas.setText("Ayam Geprek");

        mMenuKantinDuaBelas.setText("Nasi Uduk");

        mMenuKantinTigaBelas.setText("Ayam Bakar");

        mMenuKantinEmpatBelas.setText("Ayam Goreng");

        mMenuKantinLimaBelas.setText("Seblak");

        mNoKantinEmpat.setText("4. Warung");

        mMenuKantinEnamBelas.setText("Nasi Bakar");

        mMenuKantinTujuhBelas.setText("Oreo Goreng");

        mMenuKantinDelapanBelas.setText("Nextar");

        mMenuKantinSembilanBelas.setText("Tempe");

        mMenuKantinDuaPuluh.setText("Tahu");

        mNoKantinLima.setText("5. Tansu");

        mMenuKantinDuaSatu.setText("Soto Lamongan");

        mMenuKantinDuaDua.setText("Rendang");

        mMenuKantinDuaTiga.setText("Sate Padang");

        mMenuKantinDuaEmpat.setText("Ayam McD");

        mMenuKantinDuaLima.setText("Kentang Goreng");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/image/back.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(mDaftarMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mNoKantinSatu)
                            .addComponent(mMenuKantinSatu)
                            .addComponent(mMenuKantinDua)
                            .addComponent(mMenuKantinTiga)
                            .addComponent(mMenuKantinEmpat)
                            .addComponent(mMenuKantinLima))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mNoKantinDua)
                            .addComponent(mMenuKantinEnam)
                            .addComponent(mMenuKantinSepuluh)
                            .addComponent(mMenuKantinSembilan)
                            .addComponent(mMenuKantinDelapan)
                            .addComponent(mMenuKantinTujuh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mMenuKantinSebelas)
                            .addComponent(mNoKantinTiga)
                            .addComponent(mMenuKantinDuaBelas)
                            .addComponent(mMenuKantinTigaBelas)
                            .addComponent(mMenuKantinEmpatBelas)
                            .addComponent(mMenuKantinLimaBelas))))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mNoKantinEmpat)
                    .addComponent(mMenuKantinEnamBelas)
                    .addComponent(mMenuKantinTujuhBelas)
                    .addComponent(mMenuKantinDelapanBelas)
                    .addComponent(mMenuKantinSembilanBelas)
                    .addComponent(mMenuKantinDuaPuluh))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mMenuKantinDuaLima)
                    .addComponent(mMenuKantinDuaEmpat)
                    .addComponent(mMenuKantinDuaTiga)
                    .addComponent(mMenuKantinDuaDua)
                    .addComponent(mMenuKantinDuaSatu)
                    .addComponent(mNoKantinLima))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mDaftarMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mNoKantinSatu)
                    .addComponent(mNoKantinDua)
                    .addComponent(mNoKantinTiga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mMenuKantinSatu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mMenuKantinEnam)
                        .addComponent(mMenuKantinSebelas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mMenuKantinDua)
                    .addComponent(mMenuKantinTujuh)
                    .addComponent(mMenuKantinDuaBelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mMenuKantinTiga)
                    .addComponent(mMenuKantinDelapan)
                    .addComponent(mMenuKantinTigaBelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mMenuKantinEmpat)
                    .addComponent(mMenuKantinSembilan)
                    .addComponent(mMenuKantinEmpatBelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mMenuKantinLima)
                    .addComponent(mMenuKantinSepuluh)
                    .addComponent(mMenuKantinLimaBelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mNoKantinEmpat)
                    .addComponent(mNoKantinLima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mMenuKantinEnamBelas)
                    .addComponent(mMenuKantinDuaSatu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mMenuKantinTujuhBelas)
                    .addComponent(mMenuKantinDuaDua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mMenuKantinDelapanBelas)
                    .addComponent(mMenuKantinDuaTiga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mMenuKantinSembilanBelas)
                    .addComponent(mMenuKantinDuaEmpat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mMenuKantinDuaPuluh)
                    .addComponent(mMenuKantinDuaLima)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarListMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarListMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarListMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarListMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mDaftarMenu;
    private javax.swing.JLabel mMenuKantinDelapan;
    private javax.swing.JLabel mMenuKantinDelapanBelas;
    private javax.swing.JLabel mMenuKantinDua;
    private javax.swing.JLabel mMenuKantinDuaBelas;
    private javax.swing.JLabel mMenuKantinDuaDua;
    private javax.swing.JLabel mMenuKantinDuaEmpat;
    private javax.swing.JLabel mMenuKantinDuaLima;
    private javax.swing.JLabel mMenuKantinDuaPuluh;
    private javax.swing.JLabel mMenuKantinDuaSatu;
    private javax.swing.JLabel mMenuKantinDuaTiga;
    private javax.swing.JLabel mMenuKantinEmpat;
    private javax.swing.JLabel mMenuKantinEmpatBelas;
    private javax.swing.JLabel mMenuKantinEnam;
    private javax.swing.JLabel mMenuKantinEnamBelas;
    private javax.swing.JLabel mMenuKantinLima;
    private javax.swing.JLabel mMenuKantinLimaBelas;
    private javax.swing.JLabel mMenuKantinSatu;
    private javax.swing.JLabel mMenuKantinSebelas;
    private javax.swing.JLabel mMenuKantinSembilan;
    private javax.swing.JLabel mMenuKantinSembilanBelas;
    private javax.swing.JLabel mMenuKantinSepuluh;
    private javax.swing.JLabel mMenuKantinTiga;
    private javax.swing.JLabel mMenuKantinTigaBelas;
    private javax.swing.JLabel mMenuKantinTujuh;
    private javax.swing.JLabel mMenuKantinTujuhBelas;
    private javax.swing.JLabel mNoKantinDua;
    private javax.swing.JLabel mNoKantinEmpat;
    private javax.swing.JLabel mNoKantinLima;
    private javax.swing.JLabel mNoKantinSatu;
    private javax.swing.JLabel mNoKantinTiga;
    // End of variables declaration//GEN-END:variables
}
